// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDpseAPU0IPjFOlW8Y9TGiEPTMAKbXr0o',
    appId: '1:758084983791:web:8b1da4fc18f211366d741a',
    messagingSenderId: '758084983791',
    projectId: 'nursing-hackathon',
    authDomain: 'nursing-hackathon.firebaseapp.com',
    storageBucket: 'nursing-hackathon.appspot.com',
    measurementId: 'G-3RM32GJ3WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtYt3vr086wJVhkaQIjlY7HBKCNDrJsqE',
    appId: '1:758084983791:android:d896dc07a0635ca86d741a',
    messagingSenderId: '758084983791',
    projectId: 'nursing-hackathon',
    storageBucket: 'nursing-hackathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUmIpkecitte9HmEL4mYyRLEBuolBkcBs',
    appId: '1:758084983791:ios:3f374b6eab2c8a246d741a',
    messagingSenderId: '758084983791',
    projectId: 'nursing-hackathon',
    storageBucket: 'nursing-hackathon.appspot.com',
    iosBundleId: 'com.example.hackathonProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUmIpkecitte9HmEL4mYyRLEBuolBkcBs',
    appId: '1:758084983791:ios:451310d33357676f6d741a',
    messagingSenderId: '758084983791',
    projectId: 'nursing-hackathon',
    storageBucket: 'nursing-hackathon.appspot.com',
    iosBundleId: 'com.example.hackathonProject.RunnerTests',
  );
}
